services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: "./backendSleeper"
    volumes:
      - /app/node_modules
      - ./backendSleeper:/app

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./sleeper
    volumes:
      - /app/node_modules
      - ./sleeper:/app
